spring:
  profiles:
    active: "dev"
  application:
    name: "bizlic-web"
    
server:
  context-path: "/bizlic"
  servlet-path: "/"
  port: 8080

contract:
  #ctAddr: "0x85EA9e5229306D7D73ED41CBE427F241D6717e5B"  #合约地址
  ctAddr: "0x278E3b3840eAf71CD876428F5479c223e2EDCf3D" #合约地址
  startAddr:  "************************************"   #顶级节点地址（好像没用到）
  #sendAddr:  "0xaefe184653e506426daab8369504ce3a2d95b68c"   #from地址
  sendAddr:  "0x88f189d467250ab1b527ab5cb82aea5bf1987adb"   #dev 环境下的
  #sendAddrPk:  "e08736ed03b3d08d2e07ce89600d33664656f4f4073875cda78a476607d36570"  #私钥
  sendAddrPk:  "ef53cf43b0edc75d9e68cb1652e4b8d1d7e10aafa5a895ce5b32bd5b514cecc2"   #dev 环境下的私钥。
  gasPrice: 20000000000 # Gas Price越高，交易优先级越高，打包交易速度越快。
  gasLimit: 1500000  # Gas Limit 是用户愿意为执行某个操作或确认交易支付的最大Gas量（最少21,000）
  isAddGas: false #是否启用按当前市价进行加权矿工费用
  addGas:   2000000000 #所增加费用
  url: "http://localhost:8545/" #正式网 or 测试网
